import { describe, it, expect } from 'vitest';
import { authStack, createSupabaseMfaUser as createMfaUser, currentCode, supabaseEnrollTotp as enrollTotp, getUser, signIn, signUp, tokenClaims, uniqueEmail, supabaseVerifyTotp as verifyTotp } from './support/authStack';

/**
 * Proves the local Supabase Auth stack behaves the way Milestone 2 relies on, with no mocking:
 * password sign-in gives an aal1 session; a verified authenticator-app code gives aal2; wrong codes
 * and garbage tokens are refused.
 */
describe('Local Supabase Auth stack (real users, real TOTP)', () => {
  it('is reachable and configured with TOTP multifactor enabled', () => {
    const { apiUrl, anonKey } = authStack();
    expect(apiUrl).toMatch(/^http:\/\/(127\.0\.0\.1|localhost):\d+$/); // never a hosted project
    expect(anonKey.length).toBeGreaterThan(20);
  });

  it('a new user starts at aal1, and a TOTP code generated by otplib upgrades the session to aal2', async () => {
    const email = uniqueEmail('flow');
    const aal1 = await signUp(email);
    expect(aal1.aal).toBe('aal1');

    const factor = await enrollTotp(aal1);
    const before = await getUser(aal1.accessToken);
    expect(before.body.factors[0].status).toBe('unverified');

    const verified = await verifyTotp(aal1, factor, currentCode(factor.secret));
    expect(verified.status).toBe(200);
    expect(verified.session!.aal).toBe('aal2');
    expect(verified.session!.userId).toBe(aal1.userId);

    const after = await getUser(verified.session!.accessToken);
    expect(after.status).toBe(200);
    expect(after.body.factors[0].status).toBe('verified');
  });

  it('signing in again with only the password gives an aal1 session, even after MFA is set up', async () => {
    const { email, session } = await createMfaUser('relogin');
    expect(session.aal).toBe('aal2');
    const again = await signIn(email);
    expect(again.aal).toBe('aal1');
    expect(tokenClaims(again.accessToken).sub).toBe(session.userId);
  });

  it('a wrong code is refused and does not upgrade the session', async () => {
    const aal1 = await signUp(uniqueEmail('wrongcode'));
    const factor = await enrollTotp(aal1);
    const wrong = currentCode(factor.secret) === '000000' ? '000001' : '000000';
    const result = await verifyTotp(aal1, factor, wrong);
    expect(result.status).toBe(422);
    expect(result.body.error_code).toBe('mfa_verification_failed');
    expect(result.session).toBeNull();
  });

  it('the auth server rejects a garbage token and a token with a broken signature', async () => {
    expect((await getUser('garbage')).status).toBe(403);
    const { session } = await createMfaUser('tamper');
    const [h, p, s] = session.accessToken.split('.');
    const forgedPayload = Buffer.from(JSON.stringify({ ...tokenClaims(session.accessToken), aal: 'aal2', sub: '00000000-0000-0000-0000-000000000000' })).toString('base64url');
    expect((await getUser(`${h}.${forgedPayload}.${s}`)).status).toBeGreaterThanOrEqual(400);
  });

  it('two users get different identities', async () => {
    const a = await createMfaUser('userA');
    const b = await createMfaUser('userB');
    expect(a.session.userId).not.toBe(b.session.userId);
  });
});
