import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Builds the two SQL scripts a person can paste into the Supabase dashboard's SQL Editor, from the
 * real migration files, so they can never drift from what `npm run migrate` applies.
 */
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (p: string) => fs.readFileSync(path.join(root, p), 'utf8');

const TABLES = ['creator', 'developer', 'connection', 'project', 'repository', 'agreement_template', 'door', 'door_repository', 'workspace', 'mirror_snapshot', 'event'];
const MIGRATION_LOCK_ID = 7_021_001; // the same advisory lock server/migrationRunner.ts takes

export function buildApplySql(): string {
  const migrations = fs
    .readdirSync(path.join(root, 'server', 'migrations'))
    .filter((n) => /^\d+_.+\.sql$/.test(n) && !n.startsWith('001_'))
    .sort();
  const blocks = migrations.map((file, i) => {
    const body = read(`server/migrations/${file}`);
    if (body.includes('$mig$') || body.includes('$apply$')) throw new Error(`${file} contains a reserved dollar-quote tag`);
    const tag = `apply${i}`;
    return `-- ---------------------------------------------------------------------------
-- ${file}  (skipped if it is already recorded in schema_migrations)
-- ---------------------------------------------------------------------------
DO $${tag}$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = '${file}') THEN
    EXECUTE $mig$
${body}
$mig$;
    INSERT INTO schema_migrations (version) VALUES ('${file}');
    RAISE NOTICE 'applied ${file}';
  ELSE
    RAISE NOTICE 'skipped ${file} (already applied)';
  END IF;
END
$${tag}$;
`;
  });

  const tableList = TABLES.map((t) => `'${t}'`).join(', ');
  return `-- =============================================================================
-- Custody Core: apply the pending database migrations (002 onward) and the custody_app grants.
--
-- Paste this whole script into the Supabase dashboard > SQL Editor and click Run.
-- Generated by scripts/build-deploy-sql.ts from server/migrations/*.sql and server/roles.sql.
-- Do not edit by hand; regenerate with: npm run build:deploy-sql
--
-- What it does:
--   * records migration 001 (already applied to this database by the app) after checking it is really there
--   * applies every later migration in order: 002 (hashed_timestamp constraint), 003 (database-built event chain,
--     append_event), 004 (creator email no longer unique)
--   * records each in schema_migrations exactly as \`npm run migrate\` does
--   * applies the custody_app grants (server/roles.sql): no INSERT on event, EXECUTE on append_event
-- It does NOT add, change or delete any event, project or creator.
--
-- Safe to run twice: a migration already recorded is skipped, and the grants are idempotent.
-- All-or-nothing: it runs in one transaction. If anything fails, nothing is changed.
-- =============================================================================
BEGIN;

-- Wait for (and block) the app's own migration runner, which takes this same lock.
SELECT pg_advisory_xact_lock(${MIGRATION_LOCK_ID});

CREATE TABLE IF NOT EXISTS schema_migrations (
  version TEXT PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Migration 001 was applied by the app before migrations were recorded. Do not record it unless it is there.
DO $check001$
BEGIN
  IF (SELECT count(*) FROM information_schema.tables
       WHERE table_schema = 'public' AND table_name IN (${tableList})) <> ${TABLES.length} THEN
    RAISE EXCEPTION 'Stop: migration 001 has not been applied to this database (expected the ${TABLES.length} Custody Core tables in schema public). Nothing was changed.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid = to_regclass('public.event') AND tgname = 'trg_event_append_only' AND NOT tgisinternal) THEN
    RAISE EXCEPTION 'Stop: the append-only trigger trg_event_append_only is missing from the event table. Nothing was changed.';
  END IF;
END
$check001$;

INSERT INTO schema_migrations (version) VALUES ('001_initial_schema.sql') ON CONFLICT (version) DO NOTHING;

${blocks.join('\n')}
-- ---------------------------------------------------------------------------
-- server/roles.sql  (the custody_app grants; safe to repeat)
-- ---------------------------------------------------------------------------
${read('server/roles.sql')}

COMMIT;
`;
}

const ROLE_OK = "(SELECT count(*) = 1 FROM pg_roles WHERE rolname = 'custody_app')";

export function buildVerifySql(): string {
  const all = fs.readdirSync(path.join(root, 'server', 'migrations')).filter((n) => /^\d+_.+\.sql$/.test(n)).sort();
  const names = all.map((n) => `''${n}''`).join(', ');
  const expectedList = all.join(', ');
  return `-- =============================================================================
-- Custody Core: READ-ONLY check of the database after the apply script.
--
-- Paste into the Supabase dashboard > SQL Editor and click Run. It changes nothing.
-- Generated by scripts/build-deploy-sql.ts. Do not edit by hand.
--
-- Result: one row per check. The first row is the overall result: ALL PASS or N FAILED.
-- =============================================================================
WITH checks(sort, name, expected, actual) AS (
  VALUES
  (10, 'schema_migrations lists every migration (${all.map((n) => n.slice(0, 3)).join(', ')})',
       '${expectedList}',
       CASE WHEN to_regclass('public.schema_migrations') IS NULL THEN 'table schema_migrations is missing'
            ELSE COALESCE((xpath('/row/v/text()', query_to_xml('SELECT string_agg(version, '', '' ORDER BY version) AS v FROM public.schema_migrations WHERE version IN (${names})', false, true, '')))[1]::text, 'none') END),
  (20, 'custody_app role exists', 'true', (SELECT (count(*) = 1)::text FROM pg_roles WHERE rolname = 'custody_app')),
  (30, 'custody_app has NO INSERT on event', 'false', CASE WHEN ${ROLE_OK} THEN has_table_privilege('custody_app', 'public.event', 'INSERT')::text ELSE 'role missing' END),
  (31, 'custody_app has NO UPDATE on event', 'false', CASE WHEN ${ROLE_OK} THEN has_table_privilege('custody_app', 'public.event', 'UPDATE')::text ELSE 'role missing' END),
  (32, 'custody_app has NO DELETE on event', 'false', CASE WHEN ${ROLE_OK} THEN has_table_privilege('custody_app', 'public.event', 'DELETE')::text ELSE 'role missing' END),
  (33, 'custody_app has NO TRUNCATE on event', 'false', CASE WHEN ${ROLE_OK} THEN has_table_privilege('custody_app', 'public.event', 'TRUNCATE')::text ELSE 'role missing' END),
  (34, 'custody_app CAN read event', 'true', CASE WHEN ${ROLE_OK} THEN has_table_privilege('custody_app', 'public.event', 'SELECT')::text ELSE 'role missing' END),
  (40, 'custody_app can EXECUTE append_event', 'true',
       CASE WHEN ${ROLE_OK} AND to_regprocedure('public.append_event(uuid,text,text,text,text,text,jsonb)') IS NOT NULL
            THEN has_function_privilege('custody_app', to_regprocedure('public.append_event(uuid,text,text,text,text,text,jsonb)'), 'EXECUTE')::text ELSE 'function or role missing' END),
  (41, 'the public (everyone) can NOT execute append_event', 'false',
       CASE WHEN to_regprocedure('public.append_event(uuid,text,text,text,text,text,jsonb)') IS NOT NULL
            THEN has_function_privilege('public', to_regprocedure('public.append_event(uuid,text,text,text,text,text,jsonb)'), 'EXECUTE')::text ELSE 'function missing' END),
  (42, 'append_event runs with its owner''s rights and a fixed search_path', 'true',
       COALESCE((SELECT (prosecdef AND proconfig::text LIKE '%search_path=pg_catalog, pg_temp%')::text FROM pg_proc WHERE oid = to_regprocedure('public.append_event(uuid,text,text,text,text,text,jsonb)')), 'function missing')),
  (50, 'trigger trg_event_append_only exists (blocks UPDATE and DELETE)', 'true',
       (SELECT (count(*) = 1)::text FROM pg_trigger WHERE tgrelid = to_regclass('public.event') AND tgname = 'trg_event_append_only' AND NOT tgisinternal)),
  (51, 'trigger trg_event_prevent_truncate exists (blocks TRUNCATE)', 'true',
       (SELECT (count(*) = 1)::text FROM pg_trigger WHERE tgrelid = to_regclass('public.event') AND tgname = 'trg_event_prevent_truncate' AND NOT tgisinternal)),
  (60, 'constraint chk_event_hashed_timestamp exists', 'true',
       (SELECT (count(*) = 1)::text FROM pg_constraint WHERE conrelid = to_regclass('public.event') AND conname = 'chk_event_hashed_timestamp')),
  (61, 'constraint chk_event_hash_version exists', 'true',
       (SELECT (count(*) = 1)::text FROM pg_constraint WHERE conrelid = to_regclass('public.event') AND conname = 'chk_event_hash_version')),
  (62, 'constraint chk_event_v2_canonical_payload exists', 'true',
       (SELECT (count(*) = 1)::text FROM pg_constraint WHERE conrelid = to_regclass('public.event') AND conname = 'chk_event_v2_canonical_payload')),
  (63, 'event.hashed_timestamp has no default value', 'true',
       (SELECT (column_default IS NULL)::text FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'event' AND column_name = 'hashed_timestamp')),
  (64, 'no event has an empty hashed_timestamp', '0', (SELECT count(*)::text FROM public.event WHERE hashed_timestamp = '')),
  (65, 'creator.email is not unique (a login''s email can change and be reused)', 'true',
       (SELECT (count(*) = 0)::text FROM pg_constraint con JOIN pg_attribute a ON a.attrelid = con.conrelid AND a.attnum = ANY (con.conkey)
         WHERE con.conrelid = to_regclass('public.creator') AND con.contype = 'u' AND array_length(con.conkey, 1) = 1 AND a.attname = 'email')),
  (70, 'custody_app has NO access to schema_migrations', 'false',
       CASE WHEN to_regclass('public.schema_migrations') IS NULL THEN 'table schema_migrations is missing'
            ELSE CASE WHEN ${ROLE_OK} THEN has_table_privilege('custody_app', 'public.schema_migrations', 'SELECT')::text ELSE 'role missing' END END),
  (80, 'events whose sequence number or previous-hash link is broken (should be 0)', '0',
       (SELECT count(*)::text FROM (
          SELECT seq,
                 lag(seq)  OVER (PARTITION BY project_id ORDER BY seq) AS prev_seq,
                 prev_hash,
                 lag(hash) OVER (PARTITION BY project_id ORDER BY seq) AS prior_hash
            FROM public.event) e
         WHERE (prev_seq IS NULL AND (seq <> 1 OR prev_hash <> repeat('0', 64)))
            OR (prev_seq IS NOT NULL AND (seq <> prev_seq + 1 OR prev_hash <> prior_hash))))
),
graded AS (
  SELECT sort, name, expected, actual, CASE WHEN actual = expected THEN 'PASS' ELSE 'FAIL' END AS status FROM checks
)
SELECT 0 AS "#", CASE WHEN count(*) FILTER (WHERE status = 'FAIL') = 0 THEN 'ALL PASS' ELSE count(*) FILTER (WHERE status = 'FAIL') || ' FAILED' END AS status,
       'overall result' AS check, '' AS expected, '' AS actual
  FROM graded
UNION ALL
SELECT sort, status, name, expected, actual FROM graded
UNION ALL
SELECT 90, 'INFO', 'events written by the old method (hash_version 1) / by the database (hash_version 2)', '',
       CASE WHEN EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'event' AND column_name = 'hash_version')
            THEN (xpath('/row/v/text()', query_to_xml('SELECT (count(*) FILTER (WHERE hash_version = 1) || '' / '' || count(*) FILTER (WHERE hash_version = 2)) AS v FROM public.event', false, true, '')))[1]::text
            ELSE 'not available yet (migration 003 not applied)' END
ORDER BY 1;
`;
}

export const DEPLOY_DIR = path.join(root, 'docs', 'deploy');
export const DEPLOY_FILES = { apply: 'apply-pending-migrations.sql', verify: 'verify-migrations.sql' };

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const out = DEPLOY_DIR;
  fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(path.join(out, DEPLOY_FILES.apply), buildApplySql());
  fs.writeFileSync(path.join(out, DEPLOY_FILES.verify), buildVerifySql());
  console.log('written to', path.relative(root, out));
}
