-- =============================================================================
-- Custody Core: apply the pending database migrations (002 onward) and the custody_app grants.
--
-- Paste this whole script into the Supabase dashboard > SQL Editor and click Run.
-- Generated by scripts/build-deploy-sql.ts from server/migrations/*.sql and server/roles.sql.
-- Do not edit by hand; regenerate with: npm run build:deploy-sql
--
-- What it does:
--   * records migration 001 (already applied to this database by the app) after checking it is really there
--   * applies every later migration in order: 002 (hashed_timestamp constraint), 003 (database-built event chain,
--     append_event), 004 (creator email no longer unique), 005 (authenticator-code step run by the app, with
--     the wrong-code limit, and the per-account record account_event), 006 (the git gateway: GitHub App
--     installations, gateway credentials, door rules), 007 (repository lock state), 008 (developer accounts,
--     invitations, signed agreements), 009 (scheduler: snapshot state on doors, snapshot records final)
--   * records each in schema_migrations exactly as `npm run migrate` does
--   * applies the custody_app grants (server/roles.sql): no INSERT on event or account_event, EXECUTE on
--     append_event and append_account_event, attempts can be added but never changed or deleted
--   * closes Supabase's built-in REST API (roles anon and authenticated) to every Custody Core table and
--     function, and turns on row-level security (only custody_app has a policy)
-- It does NOT set custody_app's password: a new custody_app has none (nobody can sign in as it) until the
-- server starts with APP_DB_PASSWORD, or you set one yourself (docs/deploy/README.md, "The app account's password").
-- It does NOT add, change or delete any event, project or creator.
--
-- Safe to run twice: a migration already recorded is skipped, and the grants are idempotent.
-- All-or-nothing: it runs in one transaction. If anything fails, nothing is changed.
-- =============================================================================
BEGIN;

-- Wait for (and block) the app's own migration runner, which takes this same lock.
SELECT pg_advisory_xact_lock(7021001);

CREATE TABLE IF NOT EXISTS schema_migrations (
  version TEXT PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Migration 001 was applied by the app before migrations were recorded. Do not record it unless it is there.
DO $check001$
BEGIN
  IF (SELECT count(*) FROM information_schema.tables
       WHERE table_schema = 'public' AND table_name IN ('creator', 'developer', 'connection', 'project', 'repository', 'agreement_template', 'door', 'door_repository', 'workspace', 'mirror_snapshot', 'event')) <> 11 THEN
    RAISE EXCEPTION 'Stop: migration 001 has not been applied to this database (expected the 11 Custody Core tables in schema public). Nothing was changed.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid = to_regclass('public.event') AND tgname = 'trg_event_append_only' AND NOT tgisinternal) THEN
    RAISE EXCEPTION 'Stop: the append-only trigger trg_event_append_only is missing from the event table. Nothing was changed.';
  END IF;
END
$check001$;

INSERT INTO schema_migrations (version) VALUES ('001_initial_schema.sql') ON CONFLICT (version) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 002_hashed_timestamp_constraint.sql  (skipped if it is already recorded in schema_migrations)
-- ---------------------------------------------------------------------------
DO $apply0$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = '002_hashed_timestamp_constraint.sql') THEN
    EXECUTE $mig$
-- 002: event.hashed_timestamp must never be empty, and must have no default.
-- Older databases were created with DEFAULT '' and/or an auto-named CHECK. Remove both, then add
-- the one named constraint the application and tests rely on.

ALTER TABLE event ALTER COLUMN hashed_timestamp DROP DEFAULT;

DO $$
DECLARE
  existing RECORD;
BEGIN
  FOR existing IN
    SELECT con.conname
    FROM pg_constraint con
    JOIN pg_attribute att
      ON att.attrelid = con.conrelid AND att.attnum = ANY (con.conkey)
    WHERE con.conrelid = 'event'::regclass
      AND con.contype = 'c'
      AND att.attname = 'hashed_timestamp'
  LOOP
    EXECUTE format('ALTER TABLE event DROP CONSTRAINT %I', existing.conname);
  END LOOP;
END
$$;

ALTER TABLE event
  ADD CONSTRAINT chk_event_hashed_timestamp CHECK (hashed_timestamp <> '');

$mig$;
    INSERT INTO schema_migrations (version) VALUES ('002_hashed_timestamp_constraint.sql');
    RAISE NOTICE 'applied 002_hashed_timestamp_constraint.sql';
  ELSE
    RAISE NOTICE 'skipped 002_hashed_timestamp_constraint.sql (already applied)';
  END IF;
END
$apply0$;

-- ---------------------------------------------------------------------------
-- 003_database_built_event_chain.sql  (skipped if it is already recorded in schema_migrations)
-- ---------------------------------------------------------------------------
DO $apply1$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = '003_database_built_event_chain.sql') THEN
    EXECUTE $mig$
-- 003: the database builds the event chain; the application can no longer write chain fields.
--
-- Events written before this migration keep hash_version = 1 (hashed by application code) and still
-- verify. Every event written by append_event() has hash_version = 2. See docs/EVENT_HASH_FORMAT.md.

ALTER TABLE event ADD COLUMN hash_version SMALLINT NOT NULL DEFAULT 1;
-- Exact payload text that was hashed (version 2 only). The hash covers this text byte for byte.
ALTER TABLE event ADD COLUMN canonical_payload TEXT;

ALTER TABLE event ADD CONSTRAINT chk_event_hash_version CHECK (hash_version IN (1, 2));
ALTER TABLE event ADD CONSTRAINT chk_event_v2_canonical_payload
  CHECK (hash_version = 1 OR (canonical_payload IS NOT NULL AND payload = canonical_payload::jsonb));

-- Canonical JSON text of a jsonb value:
--   * objects: keys sorted by Unicode code point (byte order of UTF-8), no whitespace
--   * arrays: order preserved
--   * strings: JSON-escaped exactly as JavaScript JSON.stringify does (non-ASCII left as is)
--   * numbers: exact decimal, no exponent, no trailing zeros ("100.0" -> "100", "1e3" -> "1000")
--   * true / false / null as literals
CREATE FUNCTION canonical_jsonb(j jsonb) RETURNS text
LANGUAGE plpgsql IMMUTABLE STRICT
SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
  kind text := jsonb_typeof(j);
  result text;
BEGIN
  IF kind = 'object' THEN
    SELECT '{' || coalesce(
             string_agg(to_jsonb(e.key)::text || ':' || public.canonical_jsonb(e.value), ',' ORDER BY e.key COLLATE "C"),
             '') || '}'
      INTO result
      FROM jsonb_each(j) AS e;
    RETURN result;
  ELSIF kind = 'array' THEN
    SELECT '[' || coalesce(string_agg(public.canonical_jsonb(a.value), ',' ORDER BY a.ord), '') || ']'
      INTO result
      FROM jsonb_array_elements(j) WITH ORDINALITY AS a(value, ord);
    RETURN result;
  ELSIF kind = 'string' OR kind = 'boolean' THEN
    RETURN j::text;
  ELSIF kind = 'number' THEN
    RETURN trim_scale(j::text::numeric)::text;
  END IF;
  RETURN 'null';
END
$$;

-- The only way to write an event. The caller says what happened; the database assigns the
-- sequence number, previous hash, timestamp and hash. None of those can be supplied.
CREATE FUNCTION append_event(
  p_project_id uuid,
  p_actor_type text,
  p_actor_id text,
  p_action text,
  p_subject_type text,
  p_subject_id text,
  p_payload jsonb
) RETURNS public.event
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
  v_seq bigint;
  v_prev_hash text;
  v_now timestamptz;
  v_ts text;
  v_canonical text;
  v_hash text;
  v_row public.event;
BEGIN
  IF p_project_id IS NULL OR p_actor_type IS NULL OR p_actor_id IS NULL OR p_action IS NULL
     OR p_subject_type IS NULL OR p_subject_id IS NULL OR p_payload IS NULL THEN
    RAISE EXCEPTION 'append_event: every argument is required' USING ERRCODE = 'null_value_not_allowed';
  END IF;
  IF p_actor_type NOT IN ('creator', 'developer', 'system', 'gateway') THEN
    RAISE EXCEPTION 'append_event: unknown actor_type %', p_actor_type USING ERRCODE = 'check_violation';
  END IF;
  IF p_actor_id ~ '^[[:space:]]*$' OR p_action ~ '^[[:space:]]*$' OR p_subject_type ~ '^[[:space:]]*$' OR p_subject_id ~ '^[[:space:]]*$' THEN
    RAISE EXCEPTION 'append_event: actor_id, action, subject_type and subject_id must not be empty'
      USING ERRCODE = 'check_violation';
  END IF;
  IF octet_length(p_payload::text) > 1048576 THEN
    RAISE EXCEPTION 'append_event: payload is larger than 1 MiB' USING ERRCODE = 'program_limit_exceeded';
  END IF;
  IF jsonb_typeof(p_payload) <> 'object' THEN
    RAISE EXCEPTION 'append_event: payload must be a JSON object' USING ERRCODE = 'check_violation';
  END IF;

  -- Lock the project so two writers cannot take the same sequence number or branch the chain.
  PERFORM 1 FROM public.project WHERE id = p_project_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'append_event: project % does not exist', p_project_id USING ERRCODE = 'foreign_key_violation';
  END IF;

  SELECT e.seq, e.hash INTO v_seq, v_prev_hash
    FROM public.event e
   WHERE e.project_id = p_project_id
   ORDER BY e.seq DESC
   LIMIT 1;
  IF NOT FOUND THEN
    v_seq := 0;
    v_prev_hash := repeat('0', 64);
  END IF;
  v_seq := v_seq + 1;

  v_now := clock_timestamp();
  v_ts := to_char(v_now AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
  v_canonical := public.canonical_jsonb(p_payload);

  -- Hash input: one JSON object, keys in alphabetical order, no whitespace, payload embedded as
  -- its canonical text. Identical to what shared/crypto.ts builds for hash_version 2.
  v_hash := encode(sha256(convert_to(
    '{"action":' || to_jsonb(p_action)::text ||
    ',"actor_id":' || to_jsonb(p_actor_id)::text ||
    ',"actor_type":' || to_jsonb(p_actor_type)::text ||
    ',"payload":' || v_canonical ||
    ',"prev_hash":' || to_jsonb(v_prev_hash)::text ||
    ',"project_id":' || to_jsonb(p_project_id::text)::text ||
    ',"seq":' || v_seq::text ||
    ',"subject_id":' || to_jsonb(p_subject_id)::text ||
    ',"subject_type":' || to_jsonb(p_subject_type)::text ||
    ',"timestamp":' || to_jsonb(v_ts)::text ||
    '}', 'UTF8')), 'hex');

  INSERT INTO public.event (
    seq, project_id, actor_type, actor_id, action, subject_type, subject_id,
    payload, prev_hash, hash, seed_signature_id, hashed_timestamp, created_at, updated_at,
    hash_version, canonical_payload
  ) VALUES (
    v_seq, p_project_id, p_actor_type, p_actor_id, p_action, p_subject_type, p_subject_id,
    p_payload, v_prev_hash, v_hash, '', v_ts, v_now, v_now,
    2, v_canonical
  ) RETURNING * INTO v_row;

  RETURN v_row;
END
$$;

REVOKE ALL ON FUNCTION append_event(uuid, text, text, text, text, text, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION canonical_jsonb(jsonb) FROM PUBLIC;

$mig$;
    INSERT INTO schema_migrations (version) VALUES ('003_database_built_event_chain.sql');
    RAISE NOTICE 'applied 003_database_built_event_chain.sql';
  ELSE
    RAISE NOTICE 'skipped 003_database_built_event_chain.sql (already applied)';
  END IF;
END
$apply1$;

-- ---------------------------------------------------------------------------
-- 004_creator_email_not_unique.sql  (skipped if it is already recorded in schema_migrations)
-- ---------------------------------------------------------------------------
DO $apply2$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = '004_creator_email_not_unique.sql') THEN
    EXECUTE $mig$
-- 004: creator.email is contact information, not identity.
--
-- A creator is identified by creator.identity_id (the login system's user id), never by email. Emails change,
-- and a login provider may hand an address that someone gave up to a different person later. With a UNIQUE
-- email, that second person was locked out of Custody Core for good. Remove the uniqueness; the application
-- keeps the email current instead.

DO $$
DECLARE
  existing RECORD;
BEGIN
  FOR existing IN
    SELECT con.conname
    FROM pg_constraint con
    JOIN pg_attribute att
      ON att.attrelid = con.conrelid AND att.attnum = ANY (con.conkey)
    WHERE con.conrelid = 'creator'::regclass
      AND con.contype = 'u'
      AND array_length(con.conkey, 1) = 1
      AND att.attname = 'email'
  LOOP
    EXECUTE format('ALTER TABLE creator DROP CONSTRAINT %I', existing.conname);
  END LOOP;
END
$$;

$mig$;
    INSERT INTO schema_migrations (version) VALUES ('004_creator_email_not_unique.sql');
    RAISE NOTICE 'applied 004_creator_email_not_unique.sql';
  ELSE
    RAISE NOTICE 'skipped 004_creator_email_not_unique.sql (already applied)';
  END IF;
END
$apply2$;

-- ---------------------------------------------------------------------------
-- 005_own_second_factor.sql  (skipped if it is already recorded in schema_migrations)
-- ---------------------------------------------------------------------------
DO $apply3$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = '005_own_second_factor.sql') THEN
    EXECUTE $mig$
-- 005: Custody Core runs the authenticator-app (second factor) step itself.
--
-- Supabase Auth keeps handling email and password. The 6-digit code step moves here so that wrong codes can
-- be limited: Supabase's own code-check endpoint is public and cannot be limited on every plan, so a limit
-- that only watched our server could be bypassed by guessing there. Codes are now checked only by this
-- server, against keys stored here (encrypted by the server; the database never sees a key in the clear).

-- One row per authenticator. Only one verified authenticator per login.
CREATE TABLE mfa_factor (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  identity_id TEXT NOT NULL,              -- the login system's user id (creator.identity_id)
  secret_ciphertext TEXT NOT NULL,        -- AES-256-GCM, key held by the server only
  status TEXT NOT NULL CHECK (status IN ('unverified', 'verified', 'abandoned')),
  last_used_step BIGINT,                  -- TOTP time step of the last accepted code (blocks reuse)
  locked_until TIMESTAMPTZ,               -- set after too many wrong codes
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  verified_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_mfa_factor_one_verified ON mfa_factor (identity_id) WHERE status = 'verified';
CREATE INDEX idx_mfa_factor_identity ON mfa_factor (identity_id);

-- Every code attempt, kept in the database so limits survive restarts and cover every server instance.
CREATE TABLE mfa_attempt (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  factor_id UUID NOT NULL REFERENCES mfa_factor (id),
  identity_id TEXT NOT NULL,
  outcome TEXT NOT NULL CHECK (outcome IN ('accepted', 'wrong_code', 'reused_code', 'locked')),
  attempted_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX idx_mfa_attempt_factor_time ON mfa_attempt (factor_id, attempted_at);

-- A login session (Supabase session id) that has passed the code step on this server.
CREATE TABLE mfa_session (
  session_id TEXT PRIMARY KEY,
  identity_id TEXT NOT NULL,
  factor_id UUID NOT NULL REFERENCES mfa_factor (id),
  verified_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Logins that had a verified authenticator in Supabase's old code step when this migration ran. Setting up an
-- authenticator here is refused for them until the operator clears the row (docs/LOGIN_SETUP.md): otherwise
-- whoever holds the password could set up their own and take the account. Recorded here, at deploy time, so
-- that removing the old authenticator on the Supabase side (possible after guessing its code there) does not
-- lift the block. On a database without Supabase Auth (tests), there is nothing to record.
CREATE TABLE mfa_legacy_reset (
  identity_id TEXT PRIMARY KEY,
  found_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  cleared_at TIMESTAMPTZ                  -- set by the operator after confirming the person
);
DO $legacy$
BEGIN
  IF to_regclass('auth.mfa_factors') IS NOT NULL THEN
    EXECUTE $q$INSERT INTO mfa_legacy_reset (identity_id)
               SELECT DISTINCT user_id::text FROM auth.mfa_factors WHERE status::text = 'verified'
               ON CONFLICT (identity_id) DO NOTHING$q$;
  END IF;
END
$legacy$;

-- ---------------------------------------------------------------------------------------------------------
-- Account record: an append-only, hash-chained log per login, for things that belong to the account rather
-- than to one project (for example a lockout after too many wrong codes). Built by the database, exactly
-- like the project event chain (see docs/EVENT_HASH_FORMAT.md, "Account events").
-- ---------------------------------------------------------------------------------------------------------
CREATE TABLE account_event (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id TEXT NOT NULL,               -- the login system's user id
  seq BIGINT NOT NULL,
  actor_type TEXT NOT NULL,
  actor_id TEXT NOT NULL,
  action TEXT NOT NULL,
  payload JSONB NOT NULL,
  canonical_payload TEXT NOT NULL,
  prev_hash CHAR(64) NOT NULL,
  hash CHAR(64) NOT NULL,
  hashed_timestamp TEXT NOT NULL CHECK (hashed_timestamp <> ''),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_account_event_seq UNIQUE (account_id, seq),
  CONSTRAINT chk_account_event_payload CHECK (payload = canonical_payload::jsonb)
);

CREATE FUNCTION reject_account_event_change() RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, pg_temp
AS $$
BEGIN
  RAISE EXCEPTION 'Table account_event is append-only: % operations are strictly forbidden.', TG_OP;
END
$$;

CREATE TRIGGER trg_account_event_append_only
  BEFORE UPDATE OR DELETE ON account_event
  FOR EACH ROW EXECUTE FUNCTION reject_account_event_change();
CREATE TRIGGER trg_account_event_prevent_truncate
  BEFORE TRUNCATE ON account_event
  FOR EACH STATEMENT EXECUTE FUNCTION reject_account_event_change();

CREATE FUNCTION append_account_event(
  p_account_id text,
  p_actor_type text,
  p_actor_id text,
  p_action text,
  p_payload jsonb
) RETURNS public.account_event
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
  v_seq bigint;
  v_prev_hash text;
  v_now timestamptz;
  v_ts text;
  v_canonical text;
  v_hash text;
  v_row public.account_event;
BEGIN
  IF p_account_id IS NULL OR p_actor_type IS NULL OR p_actor_id IS NULL OR p_action IS NULL OR p_payload IS NULL THEN
    RAISE EXCEPTION 'append_account_event: every argument is required' USING ERRCODE = 'null_value_not_allowed';
  END IF;
  IF p_actor_type NOT IN ('creator', 'developer', 'system', 'gateway') THEN
    RAISE EXCEPTION 'append_account_event: unknown actor_type %', p_actor_type USING ERRCODE = 'check_violation';
  END IF;
  IF p_account_id ~ '^[[:space:]]*$' OR p_actor_id ~ '^[[:space:]]*$' OR p_action ~ '^[[:space:]]*$' THEN
    RAISE EXCEPTION 'append_account_event: account_id, actor_id and action must not be empty' USING ERRCODE = 'check_violation';
  END IF;
  IF jsonb_typeof(p_payload) <> 'object' THEN
    RAISE EXCEPTION 'append_account_event: payload must be a JSON object' USING ERRCODE = 'check_violation';
  END IF;
  IF octet_length(p_payload::text) > 65536 THEN
    RAISE EXCEPTION 'append_account_event: payload is larger than 64 KiB' USING ERRCODE = 'program_limit_exceeded';
  END IF;

  -- One writer at a time per account, so sequence numbers and links never branch.
  PERFORM pg_advisory_xact_lock(hashtextextended('account_event:' || p_account_id, 0));

  SELECT e.seq, e.hash INTO v_seq, v_prev_hash
    FROM public.account_event e
   WHERE e.account_id = p_account_id
   ORDER BY e.seq DESC
   LIMIT 1;
  IF NOT FOUND THEN
    v_seq := 0;
    v_prev_hash := repeat('0', 64);
  END IF;
  v_seq := v_seq + 1;

  v_now := clock_timestamp();
  v_ts := to_char(v_now AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
  v_canonical := public.canonical_jsonb(p_payload);

  v_hash := encode(sha256(convert_to(
    '{"account_id":' || to_jsonb(p_account_id)::text ||
    ',"action":' || to_jsonb(p_action)::text ||
    ',"actor_id":' || to_jsonb(p_actor_id)::text ||
    ',"actor_type":' || to_jsonb(p_actor_type)::text ||
    ',"payload":' || v_canonical ||
    ',"prev_hash":' || to_jsonb(v_prev_hash)::text ||
    ',"seq":' || v_seq::text ||
    ',"timestamp":' || to_jsonb(v_ts)::text ||
    '}', 'UTF8')), 'hex');

  INSERT INTO public.account_event (
    account_id, seq, actor_type, actor_id, action, payload, canonical_payload, prev_hash, hash, hashed_timestamp, created_at
  ) VALUES (
    p_account_id, v_seq, p_actor_type, p_actor_id, p_action, p_payload, v_canonical, v_prev_hash, v_hash, v_ts, v_now
  ) RETURNING * INTO v_row;

  RETURN v_row;
END
$$;

REVOKE ALL ON FUNCTION append_account_event(text, text, text, text, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION reject_account_event_change() FROM PUBLIC;

$mig$;
    INSERT INTO schema_migrations (version) VALUES ('005_own_second_factor.sql');
    RAISE NOTICE 'applied 005_own_second_factor.sql';
  ELSE
    RAISE NOTICE 'skipped 005_own_second_factor.sql (already applied)';
  END IF;
END
$apply3$;

-- ---------------------------------------------------------------------------
-- 006_git_gateway.sql  (skipped if it is already recorded in schema_migrations)
-- ---------------------------------------------------------------------------
DO $apply4$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = '006_git_gateway.sql') THEN
    EXECUTE $mig$
-- 006: the git gateway.
--
-- A creator connects their GitHub organization once (a GitHub App installation). A door gives one outside
-- developer a gateway credential for chosen repositories of one project. The developer's git remote is
-- Custody Core, never GitHub: the gateway checks the credential on every request, lets them push only to
-- branches under door/<door id>/, scans every push for secrets, and only then forwards it to GitHub.

-- The GitHub App installation a creator connected (one per creator). The installation id is not a secret;
-- the App's private key stays in the server's environment.
CREATE TABLE github_installation (
  creator_id UUID PRIMARY KEY REFERENCES creator (id) ON DELETE CASCADE,
  installation_id BIGINT NOT NULL CHECK (installation_id > 0),
  account_login TEXT NOT NULL,
  account_type TEXT NOT NULL,
  connected_by_github_login TEXT NOT NULL,   -- the GitHub user who proved access to the installation
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Doors are for a developer named by email; developer accounts and signing come later.
ALTER TABLE door ADD COLUMN developer_email TEXT;
ALTER TABLE door ADD CONSTRAINT chk_door_status
  CHECK (status IN ('draft', 'awaiting_signature', 'opening', 'open', 'closing', 'closed', 'failed'));
ALTER TABLE door_repository ADD CONSTRAINT chk_door_repository_access CHECK (access IN ('read', 'write'));
CREATE INDEX idx_door_repository_repository ON door_repository (repository_id);

-- A closed door stays closed: a new door is a new record.
CREATE FUNCTION door_closed_is_final() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.status = 'closed' AND NEW.status <> 'closed' THEN
    RAISE EXCEPTION 'door %: a closed door cannot be reopened', OLD.id USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END
$$;
CREATE TRIGGER trg_door_closed_is_final BEFORE UPDATE ON door FOR EACH ROW EXECUTE FUNCTION door_closed_is_final();

-- The secret the developer's git client sends. Only its SHA-256 is stored; the value is shown once.
CREATE TABLE gateway_credential (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  door_id UUID NOT NULL REFERENCES door (id) ON DELETE CASCADE,
  token_hash CHAR(64) NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_used_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ
);
CREATE INDEX idx_gateway_credential_door ON gateway_credential (door_id);

-- A credential's secret and door never change, and a revocation can never be undone.
CREATE FUNCTION gateway_credential_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.token_hash <> OLD.token_hash OR NEW.door_id <> OLD.door_id OR NEW.created_at <> OLD.created_at THEN
    RAISE EXCEPTION 'gateway_credential %: only last_used_at and revoked_at can change', OLD.id USING ERRCODE = 'check_violation';
  END IF;
  IF OLD.revoked_at IS NOT NULL AND NEW.revoked_at IS DISTINCT FROM OLD.revoked_at THEN
    RAISE EXCEPTION 'gateway_credential %: a revocation cannot be undone', OLD.id USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END
$$;
CREATE TRIGGER trg_gateway_credential_guard BEFORE UPDATE ON gateway_credential
  FOR EACH ROW EXECUTE FUNCTION gateway_credential_guard();

$mig$;
    INSERT INTO schema_migrations (version) VALUES ('006_git_gateway.sql');
    RAISE NOTICE 'applied 006_git_gateway.sql';
  ELSE
    RAISE NOTICE 'skipped 006_git_gateway.sql (already applied)';
  END IF;
END
$apply4$;

-- ---------------------------------------------------------------------------
-- 007_repository_lock.sql  (skipped if it is already recorded in schema_migrations)
-- ---------------------------------------------------------------------------
DO $apply5$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = '007_repository_lock.sql') THEN
    EXECUTE $mig$
-- 007: locking a project's repositories on GitHub.
--
-- When a repository is added to a project, Custody Core puts a ruleset on it: the default branch cannot be
-- deleted or force-pushed by anyone except the Custody Core GitHub App, and forking is turned off where GitHub
-- allows it. The repository counts as locked (locked_at) only after the ruleset has been read back from GitHub
-- and checked. Every check after that reads it back again and records it if it was removed or changed.

ALTER TABLE repository ADD COLUMN lock_ruleset_id BIGINT;
ALTER TABLE repository ADD COLUMN lock_checked_at TIMESTAMPTZ;
-- Why the last attempt did not lock it, in words for the creator (for example the GitHub plan does not allow
-- rulesets on private repositories). Empty when locked.
ALTER TABLE repository ADD COLUMN lock_error TEXT;

$mig$;
    INSERT INTO schema_migrations (version) VALUES ('007_repository_lock.sql');
    RAISE NOTICE 'applied 007_repository_lock.sql';
  ELSE
    RAISE NOTICE 'skipped 007_repository_lock.sql (already applied)';
  END IF;
END
$apply5$;

-- ---------------------------------------------------------------------------
-- 008_developer_accounts_and_signing.sql  (skipped if it is already recorded in schema_migrations)
-- ---------------------------------------------------------------------------
DO $apply6$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = '008_developer_accounts_and_signing.sql') THEN
    EXECUTE $mig$
-- 008: developer accounts, invitations and agreement signing.
--
-- A door now opens only after the invited developer has (1) signed in with their own account, which has the same
-- required authenticator-code step as creators, (2) accepted the invitation with the email address it was sent to,
-- and (3) signed the door's agreement with a key that never leaves their own device. The server checks the
-- signature, records it in the project's event record, and only then opens the door. The gateway credential is
-- given to the developer, not to the creator.
--
--   draft --invite--> awaiting_signature --developer signs--> open --close--> closed

-- A developer is a login (identity_id), like a creator. Email is contact information, not identity (see 004).
DO $$
DECLARE
  existing RECORD;
BEGIN
  FOR existing IN
    SELECT con.conname FROM pg_constraint con
      JOIN pg_attribute att ON att.attrelid = con.conrelid AND att.attnum = ANY (con.conkey)
     WHERE con.conrelid = 'developer'::regclass AND con.contype = 'u' AND array_length(con.conkey, 1) = 1 AND att.attname = 'email'
  LOOP
    EXECUTE format('ALTER TABLE developer DROP CONSTRAINT %I', existing.conname);
  END LOOP;
END
$$;

-- Signing keys a developer has registered. Only the public half is ever sent to the server. A developer has at most
-- one current key; registering a new one (a new device) retires the old one, and both stay on record.
CREATE TABLE developer_key (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  developer_id UUID NOT NULL REFERENCES developer (id) ON DELETE CASCADE,
  algorithm TEXT NOT NULL CHECK (algorithm = 'ECDSA-P256-SHA256'),
  public_key_spki TEXT NOT NULL,              -- base64 DER SubjectPublicKeyInfo
  fingerprint CHAR(64) NOT NULL CHECK (fingerprint ~ '^[0-9a-f]{64}$'),  -- SHA-256 of the DER key
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  retired_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_developer_key_current ON developer_key (developer_id) WHERE retired_at IS NULL;

CREATE FUNCTION developer_key_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.public_key_spki <> OLD.public_key_spki OR NEW.fingerprint <> OLD.fingerprint OR NEW.developer_id <> OLD.developer_id
     OR NEW.algorithm <> OLD.algorithm OR NEW.created_at <> OLD.created_at THEN
    RAISE EXCEPTION 'developer_key %: a registered key cannot be changed', OLD.id USING ERRCODE = 'check_violation';
  END IF;
  IF OLD.retired_at IS NOT NULL AND NEW.retired_at IS DISTINCT FROM OLD.retired_at THEN
    RAISE EXCEPTION 'developer_key %: a retired key stays retired', OLD.id USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END
$$;
CREATE TRIGGER trg_developer_key_guard BEFORE UPDATE ON developer_key FOR EACH ROW EXECUTE FUNCTION developer_key_guard();

-- An invitation link. Only the SHA-256 of its secret is stored. It works only for a login with this email address.
CREATE TABLE door_invite (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  door_id UUID NOT NULL REFERENCES door (id) ON DELETE CASCADE,
  token_hash CHAR(64) NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  email TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL,
  accepted_at TIMESTAMPTZ,
  accepted_by_developer UUID REFERENCES developer (id),
  revoked_at TIMESTAMPTZ
);
CREATE INDEX idx_door_invite_door ON door_invite (door_id);

-- The agreement is fixed when the invitation is sent: its exact text and SHA-256 are stored on the door, and the
-- developer signs that SHA-256. After signing, nothing about it can change.
ALTER TABLE door ADD COLUMN agreement_version TEXT;
ALTER TABLE door ADD COLUMN agreement_text TEXT;
ALTER TABLE door ADD COLUMN agreement_sha256 CHAR(64) CHECK (agreement_sha256 ~ '^[0-9a-f]{64}$');
ALTER TABLE door ADD COLUMN agreement_signed_at TIMESTAMPTZ;
ALTER TABLE door ADD COLUMN agreement_signed_message TEXT;   -- the exact bytes signed (UTF-8 JSON)
ALTER TABLE door ADD COLUMN agreement_signature TEXT;        -- base64, IEEE P1363 (r || s)
ALTER TABLE door ADD COLUMN agreement_key_id UUID REFERENCES developer_key (id);

CREATE FUNCTION door_agreement_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  -- Once sent (the door left draft), the agreement text is fixed.
  IF OLD.agreement_sha256 IS NOT NULL AND OLD.status <> 'draft' AND (
       NEW.agreement_text IS DISTINCT FROM OLD.agreement_text OR NEW.agreement_sha256 IS DISTINCT FROM OLD.agreement_sha256
       OR NEW.agreement_version IS DISTINCT FROM OLD.agreement_version) THEN
    RAISE EXCEPTION 'door %: the agreement cannot change after it was sent', OLD.id USING ERRCODE = 'check_violation';
  END IF;
  -- Once signed, the signature and who signed are fixed.
  IF OLD.agreement_signed_at IS NOT NULL AND (
       NEW.agreement_signed_at IS DISTINCT FROM OLD.agreement_signed_at OR NEW.agreement_signature IS DISTINCT FROM OLD.agreement_signature
       OR NEW.agreement_signed_message IS DISTINCT FROM OLD.agreement_signed_message OR NEW.agreement_key_id IS DISTINCT FROM OLD.agreement_key_id
       OR NEW.developer_id IS DISTINCT FROM OLD.developer_id) THEN
    RAISE EXCEPTION 'door %: a signed agreement cannot change', OLD.id USING ERRCODE = 'check_violation';
  END IF;
  -- A door opens only with a signed agreement (doors opened before 008 are left as they are).
  IF NEW.status = 'open' AND OLD.status <> 'open' AND NEW.agreement_signed_at IS NULL THEN
    RAISE EXCEPTION 'door %: cannot open without a signed agreement', OLD.id USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END
$$;
CREATE TRIGGER trg_door_agreement_guard BEFORE UPDATE ON door FOR EACH ROW EXECUTE FUNCTION door_agreement_guard();

$mig$;
    INSERT INTO schema_migrations (version) VALUES ('008_developer_accounts_and_signing.sql');
    RAISE NOTICE 'applied 008_developer_accounts_and_signing.sql';
  ELSE
    RAISE NOTICE 'skipped 008_developer_accounts_and_signing.sql (already applied)';
  END IF;
END
$apply6$;

-- ---------------------------------------------------------------------------
-- 009_scheduler_and_snapshots.sql  (skipped if it is already recorded in schema_migrations)
-- ---------------------------------------------------------------------------
DO $apply7$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = '009_scheduler_and_snapshots.sql') THEN
    EXECUTE $mig$
-- 009: the scheduler (doors close at their end date, locks are re-checked) and backup snapshots on close.
--
-- When a door that was open closes (by the creator or at its end date), a snapshot of its work is due: for each of
-- the door's repositories, a git bundle of the default branch and the door's own branches, fetched from GitHub,
-- verified, and stored with its SHA-256. Closing never waits for it: the door records that a snapshot is pending,
-- and the scheduler takes it, retrying if GitHub or the storage is unavailable.

ALTER TABLE door ADD COLUMN snapshot_status TEXT CHECK (snapshot_status IN ('pending', 'done', 'failed'));
ALTER TABLE door ADD COLUMN snapshot_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE door ADD COLUMN snapshot_next_attempt_at TIMESTAMPTZ;
ALTER TABLE door ADD COLUMN snapshot_error TEXT;
CREATE INDEX idx_door_snapshot_pending ON door (snapshot_next_attempt_at) WHERE snapshot_status = 'pending';
CREATE INDEX idx_door_open_expiry ON door (expires_at) WHERE status IN ('draft', 'awaiting_signature', 'open');

ALTER TABLE mirror_snapshot ADD COLUMN door_id UUID REFERENCES door (id);
ALTER TABLE mirror_snapshot ADD COLUMN trigger TEXT;
ALTER TABLE mirror_snapshot ADD COLUMN refs JSONB;          -- {"refs/heads/main": "<sha>", ...} as bundled
CREATE INDEX idx_mirror_snapshot_door ON mirror_snapshot (door_id);

-- A snapshot record never changes once written.
CREATE FUNCTION mirror_snapshot_is_final() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'mirror_snapshot %: a snapshot record cannot be changed or deleted', OLD.id USING ERRCODE = 'check_violation';
END
$$;
CREATE TRIGGER trg_mirror_snapshot_is_final BEFORE UPDATE OR DELETE ON mirror_snapshot FOR EACH ROW EXECUTE FUNCTION mirror_snapshot_is_final();

$mig$;
    INSERT INTO schema_migrations (version) VALUES ('009_scheduler_and_snapshots.sql');
    RAISE NOTICE 'applied 009_scheduler_and_snapshots.sql';
  ELSE
    RAISE NOTICE 'skipped 009_scheduler_and_snapshots.sql (already applied)';
  END IF;
END
$apply7$;

-- ---------------------------------------------------------------------------
-- server/roles.sql  (the custody_app grants; safe to repeat)
-- ---------------------------------------------------------------------------
-- Custody Core Restricted Database Role: custody_app
-- This role has least-privilege permissions:
-- 1. Only SELECT and INSERT on the 'event' table (no UPDATE, no DELETE, no TRUNCATE, no trigger modification/ownership).
-- 2. SELECT, INSERT, UPDATE on other domain tables.
-- 3. The application runtime must connect using this role, never as the 'postgres' superuser.

DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'custody_app') THEN
    -- No password here: this file is public. The server sets it from APP_DB_PASSWORD after running this file;
    -- until then nobody can sign in as custody_app.
    CREATE ROLE custody_app WITH LOGIN;
  END IF;
END
$$;

-- Grant schema access
GRANT USAGE ON SCHEMA public TO custody_app;

-- Grant base table permissions
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO custody_app;

-- Strictly revoke mutation privileges on event table
-- Events are written only through append_event(), which assigns seq, prev_hash, timestamp and hash.
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON TABLE event FROM custody_app;
GRANT EXECUTE ON FUNCTION append_event(uuid, text, text, text, text, text, jsonb) TO custody_app;

-- Second factor (migration 005): attempts are a record, so the app may add and read them but never change them.
-- Account events, like project events, are written only through append_account_event().
REVOKE UPDATE, DELETE, TRUNCATE ON TABLE mfa_attempt FROM custody_app;
REVOKE UPDATE, DELETE, TRUNCATE ON TABLE mfa_session FROM custody_app;
REVOKE DELETE, TRUNCATE ON TABLE mfa_factor FROM custody_app;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON TABLE account_event FROM custody_app;
-- Only the operator clears a reset requirement.
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON TABLE mfa_legacy_reset FROM custody_app;
GRANT EXECUTE ON FUNCTION append_account_event(text, text, text, text, jsonb) TO custody_app;

-- The app role must not be able to create objects (for example look-alike functions) in this schema.
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

-- Grant sequence permissions for identity/auto-increment columns
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO custody_app;

-- Ensure future tables grant permissions correctly if needed
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO custody_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO custody_app;

-- The migration bookkeeping table is for the admin role only; the app must not edit it.
DO $$
BEGIN
  IF to_regclass('public.schema_migrations') IS NOT NULL THEN
    REVOKE ALL ON TABLE schema_migrations FROM custody_app;
  END IF;
END
$$;

-- Supabase's built-in REST API is closed to all of the above by server/lockdown.sql, which runs after this file
-- (and inside every migration).


-- ---------------------------------------------------------------------------
-- server/lockdown.sql  (closes Supabase's REST API to our tables and functions; safe to repeat)
-- ---------------------------------------------------------------------------
-- ---------------------------------------------------------------------------------------------------------
-- Close Supabase's built-in REST API (Data API) to everything of ours.
--
-- On Supabase, every table and function in schema public is served at /rest/v1 to the roles anon and
-- authenticated, with the PUBLIC key that is in the browser, and new tables get full rights for those roles.
-- Custody Core never uses that API: all access goes through our server as custody_app. So those roles get
-- no access at all, and row-level security is on for every table (only custody_app has a policy; the
-- table owner and SECURITY DEFINER functions are not affected). On a plain PostgreSQL without those roles
-- the role-specific part is skipped.
--
-- It refers to no particular table or function, so it can run inside every migration's own transaction:
-- nothing a migration creates is ever committed while open. It runs again after server/roles.sql.
-- ---------------------------------------------------------------------------------------------------------

-- Functions are executable by PUBLIC (every role) unless revoked. Only custody_app needs any of ours, and
-- server/roles.sql grants it exactly those. The default-privileges line has no IN SCHEMA on purpose: a per-schema
-- default cannot take away PostgreSQL's global "PUBLIC may execute" default, so without this every function a
-- later migration creates would be callable through the REST API.
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

DO $$
DECLARE
  r text;
  t record;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = r) THEN
      EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA public FROM %I', r);
      EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM %I', r);
      EXECUTE format('REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM %I', r);
      EXECUTE format('REVOKE ALL ON SCHEMA public FROM %I', r);
      EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM %I', r);
      EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM %I', r);
      EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM %I', r);
    END IF;
  END LOOP;

  FOR t IN
    SELECT c.relname FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p')
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t.relname);
    -- (On the very first migration custody_app does not exist yet; roles.sql creates it and this runs again.)
    IF EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'custody_app') AND NOT EXISTS (SELECT FROM pg_catalog.pg_policies WHERE schemaname = 'public' AND tablename = t.relname AND policyname = 'custody_app_access') THEN
      EXECUTE format('CREATE POLICY custody_app_access ON public.%I FOR ALL TO custody_app USING (true) WITH CHECK (true)', t.relname);
    END IF;
  END LOOP;
END
$$;


COMMIT;
