-- =============================================================================
-- Custody Core: apply the pending database migrations (002 onward) and the custody_app grants.
--
-- Paste this whole script into the Supabase dashboard > SQL Editor and click Run.
-- Generated by scripts/build-deploy-sql.ts from server/migrations/*.sql and server/roles.sql.
-- Do not edit by hand; regenerate with: npm run build:deploy-sql
--
-- What it does:
--   * records migration 001 (already applied to this database by the app) after checking it is really there
--   * applies every later migration in order: 002 (hashed_timestamp constraint), 003 (database-built event chain,
--     append_event), 004 (creator email no longer unique)
--   * records each in schema_migrations exactly as `npm run migrate` does
--   * applies the custody_app grants (server/roles.sql): no INSERT on event, EXECUTE on append_event
-- It does NOT add, change or delete any event, project or creator.
--
-- Safe to run twice: a migration already recorded is skipped, and the grants are idempotent.
-- All-or-nothing: it runs in one transaction. If anything fails, nothing is changed.
-- =============================================================================
BEGIN;

-- Wait for (and block) the app's own migration runner, which takes this same lock.
SELECT pg_advisory_xact_lock(7021001);

CREATE TABLE IF NOT EXISTS schema_migrations (
  version TEXT PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Migration 001 was applied by the app before migrations were recorded. Do not record it unless it is there.
DO $check001$
BEGIN
  IF (SELECT count(*) FROM information_schema.tables
       WHERE table_schema = 'public' AND table_name IN ('creator', 'developer', 'connection', 'project', 'repository', 'agreement_template', 'door', 'door_repository', 'workspace', 'mirror_snapshot', 'event')) <> 11 THEN
    RAISE EXCEPTION 'Stop: migration 001 has not been applied to this database (expected the 11 Custody Core tables in schema public). Nothing was changed.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid = to_regclass('public.event') AND tgname = 'trg_event_append_only' AND NOT tgisinternal) THEN
    RAISE EXCEPTION 'Stop: the append-only trigger trg_event_append_only is missing from the event table. Nothing was changed.';
  END IF;
END
$check001$;

INSERT INTO schema_migrations (version) VALUES ('001_initial_schema.sql') ON CONFLICT (version) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 002_hashed_timestamp_constraint.sql  (skipped if it is already recorded in schema_migrations)
-- ---------------------------------------------------------------------------
DO $apply0$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = '002_hashed_timestamp_constraint.sql') THEN
    EXECUTE $mig$
-- 002: event.hashed_timestamp must never be empty, and must have no default.
-- Older databases were created with DEFAULT '' and/or an auto-named CHECK. Remove both, then add
-- the one named constraint the application and tests rely on.

ALTER TABLE event ALTER COLUMN hashed_timestamp DROP DEFAULT;

DO $$
DECLARE
  existing RECORD;
BEGIN
  FOR existing IN
    SELECT con.conname
    FROM pg_constraint con
    JOIN pg_attribute att
      ON att.attrelid = con.conrelid AND att.attnum = ANY (con.conkey)
    WHERE con.conrelid = 'event'::regclass
      AND con.contype = 'c'
      AND att.attname = 'hashed_timestamp'
  LOOP
    EXECUTE format('ALTER TABLE event DROP CONSTRAINT %I', existing.conname);
  END LOOP;
END
$$;

ALTER TABLE event
  ADD CONSTRAINT chk_event_hashed_timestamp CHECK (hashed_timestamp <> '');

$mig$;
    INSERT INTO schema_migrations (version) VALUES ('002_hashed_timestamp_constraint.sql');
    RAISE NOTICE 'applied 002_hashed_timestamp_constraint.sql';
  ELSE
    RAISE NOTICE 'skipped 002_hashed_timestamp_constraint.sql (already applied)';
  END IF;
END
$apply0$;

-- ---------------------------------------------------------------------------
-- 003_database_built_event_chain.sql  (skipped if it is already recorded in schema_migrations)
-- ---------------------------------------------------------------------------
DO $apply1$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = '003_database_built_event_chain.sql') THEN
    EXECUTE $mig$
-- 003: the database builds the event chain; the application can no longer write chain fields.
--
-- Events written before this migration keep hash_version = 1 (hashed by application code) and still
-- verify. Every event written by append_event() has hash_version = 2. See docs/EVENT_HASH_FORMAT.md.

ALTER TABLE event ADD COLUMN hash_version SMALLINT NOT NULL DEFAULT 1;
-- Exact payload text that was hashed (version 2 only). The hash covers this text byte for byte.
ALTER TABLE event ADD COLUMN canonical_payload TEXT;

ALTER TABLE event ADD CONSTRAINT chk_event_hash_version CHECK (hash_version IN (1, 2));
ALTER TABLE event ADD CONSTRAINT chk_event_v2_canonical_payload
  CHECK (hash_version = 1 OR (canonical_payload IS NOT NULL AND payload = canonical_payload::jsonb));

-- Canonical JSON text of a jsonb value:
--   * objects: keys sorted by Unicode code point (byte order of UTF-8), no whitespace
--   * arrays: order preserved
--   * strings: JSON-escaped exactly as JavaScript JSON.stringify does (non-ASCII left as is)
--   * numbers: exact decimal, no exponent, no trailing zeros ("100.0" -> "100", "1e3" -> "1000")
--   * true / false / null as literals
CREATE FUNCTION canonical_jsonb(j jsonb) RETURNS text
LANGUAGE plpgsql IMMUTABLE STRICT
SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
  kind text := jsonb_typeof(j);
  result text;
BEGIN
  IF kind = 'object' THEN
    SELECT '{' || coalesce(
             string_agg(to_jsonb(e.key)::text || ':' || public.canonical_jsonb(e.value), ',' ORDER BY e.key COLLATE "C"),
             '') || '}'
      INTO result
      FROM jsonb_each(j) AS e;
    RETURN result;
  ELSIF kind = 'array' THEN
    SELECT '[' || coalesce(string_agg(public.canonical_jsonb(a.value), ',' ORDER BY a.ord), '') || ']'
      INTO result
      FROM jsonb_array_elements(j) WITH ORDINALITY AS a(value, ord);
    RETURN result;
  ELSIF kind = 'string' OR kind = 'boolean' THEN
    RETURN j::text;
  ELSIF kind = 'number' THEN
    RETURN trim_scale(j::text::numeric)::text;
  END IF;
  RETURN 'null';
END
$$;

-- The only way to write an event. The caller says what happened; the database assigns the
-- sequence number, previous hash, timestamp and hash. None of those can be supplied.
CREATE FUNCTION append_event(
  p_project_id uuid,
  p_actor_type text,
  p_actor_id text,
  p_action text,
  p_subject_type text,
  p_subject_id text,
  p_payload jsonb
) RETURNS public.event
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
  v_seq bigint;
  v_prev_hash text;
  v_now timestamptz;
  v_ts text;
  v_canonical text;
  v_hash text;
  v_row public.event;
BEGIN
  IF p_project_id IS NULL OR p_actor_type IS NULL OR p_actor_id IS NULL OR p_action IS NULL
     OR p_subject_type IS NULL OR p_subject_id IS NULL OR p_payload IS NULL THEN
    RAISE EXCEPTION 'append_event: every argument is required' USING ERRCODE = 'null_value_not_allowed';
  END IF;
  IF p_actor_type NOT IN ('creator', 'developer', 'system', 'gateway') THEN
    RAISE EXCEPTION 'append_event: unknown actor_type %', p_actor_type USING ERRCODE = 'check_violation';
  END IF;
  IF p_actor_id ~ '^[[:space:]]*$' OR p_action ~ '^[[:space:]]*$' OR p_subject_type ~ '^[[:space:]]*$' OR p_subject_id ~ '^[[:space:]]*$' THEN
    RAISE EXCEPTION 'append_event: actor_id, action, subject_type and subject_id must not be empty'
      USING ERRCODE = 'check_violation';
  END IF;
  IF octet_length(p_payload::text) > 1048576 THEN
    RAISE EXCEPTION 'append_event: payload is larger than 1 MiB' USING ERRCODE = 'program_limit_exceeded';
  END IF;
  IF jsonb_typeof(p_payload) <> 'object' THEN
    RAISE EXCEPTION 'append_event: payload must be a JSON object' USING ERRCODE = 'check_violation';
  END IF;

  -- Lock the project so two writers cannot take the same sequence number or branch the chain.
  PERFORM 1 FROM public.project WHERE id = p_project_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'append_event: project % does not exist', p_project_id USING ERRCODE = 'foreign_key_violation';
  END IF;

  SELECT e.seq, e.hash INTO v_seq, v_prev_hash
    FROM public.event e
   WHERE e.project_id = p_project_id
   ORDER BY e.seq DESC
   LIMIT 1;
  IF NOT FOUND THEN
    v_seq := 0;
    v_prev_hash := repeat('0', 64);
  END IF;
  v_seq := v_seq + 1;

  v_now := clock_timestamp();
  v_ts := to_char(v_now AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
  v_canonical := public.canonical_jsonb(p_payload);

  -- Hash input: one JSON object, keys in alphabetical order, no whitespace, payload embedded as
  -- its canonical text. Identical to what shared/crypto.ts builds for hash_version 2.
  v_hash := encode(sha256(convert_to(
    '{"action":' || to_jsonb(p_action)::text ||
    ',"actor_id":' || to_jsonb(p_actor_id)::text ||
    ',"actor_type":' || to_jsonb(p_actor_type)::text ||
    ',"payload":' || v_canonical ||
    ',"prev_hash":' || to_jsonb(v_prev_hash)::text ||
    ',"project_id":' || to_jsonb(p_project_id::text)::text ||
    ',"seq":' || v_seq::text ||
    ',"subject_id":' || to_jsonb(p_subject_id)::text ||
    ',"subject_type":' || to_jsonb(p_subject_type)::text ||
    ',"timestamp":' || to_jsonb(v_ts)::text ||
    '}', 'UTF8')), 'hex');

  INSERT INTO public.event (
    seq, project_id, actor_type, actor_id, action, subject_type, subject_id,
    payload, prev_hash, hash, seed_signature_id, hashed_timestamp, created_at, updated_at,
    hash_version, canonical_payload
  ) VALUES (
    v_seq, p_project_id, p_actor_type, p_actor_id, p_action, p_subject_type, p_subject_id,
    p_payload, v_prev_hash, v_hash, '', v_ts, v_now, v_now,
    2, v_canonical
  ) RETURNING * INTO v_row;

  RETURN v_row;
END
$$;

REVOKE ALL ON FUNCTION append_event(uuid, text, text, text, text, text, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION canonical_jsonb(jsonb) FROM PUBLIC;

$mig$;
    INSERT INTO schema_migrations (version) VALUES ('003_database_built_event_chain.sql');
    RAISE NOTICE 'applied 003_database_built_event_chain.sql';
  ELSE
    RAISE NOTICE 'skipped 003_database_built_event_chain.sql (already applied)';
  END IF;
END
$apply1$;

-- ---------------------------------------------------------------------------
-- 004_creator_email_not_unique.sql  (skipped if it is already recorded in schema_migrations)
-- ---------------------------------------------------------------------------
DO $apply2$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = '004_creator_email_not_unique.sql') THEN
    EXECUTE $mig$
-- 004: creator.email is contact information, not identity.
--
-- A creator is identified by creator.identity_id (the login system's user id), never by email. Emails change,
-- and a login provider may hand an address that someone gave up to a different person later. With a UNIQUE
-- email, that second person was locked out of Custody Core for good. Remove the uniqueness; the application
-- keeps the email current instead.

DO $$
DECLARE
  existing RECORD;
BEGIN
  FOR existing IN
    SELECT con.conname
    FROM pg_constraint con
    JOIN pg_attribute att
      ON att.attrelid = con.conrelid AND att.attnum = ANY (con.conkey)
    WHERE con.conrelid = 'creator'::regclass
      AND con.contype = 'u'
      AND array_length(con.conkey, 1) = 1
      AND att.attname = 'email'
  LOOP
    EXECUTE format('ALTER TABLE creator DROP CONSTRAINT %I', existing.conname);
  END LOOP;
END
$$;

$mig$;
    INSERT INTO schema_migrations (version) VALUES ('004_creator_email_not_unique.sql');
    RAISE NOTICE 'applied 004_creator_email_not_unique.sql';
  ELSE
    RAISE NOTICE 'skipped 004_creator_email_not_unique.sql (already applied)';
  END IF;
END
$apply2$;

-- ---------------------------------------------------------------------------
-- server/roles.sql  (the custody_app grants; safe to repeat)
-- ---------------------------------------------------------------------------
-- Custody Core Restricted Database Role: custody_app
-- This role has least-privilege permissions:
-- 1. Only SELECT and INSERT on the 'event' table (no UPDATE, no DELETE, no TRUNCATE, no trigger modification/ownership).
-- 2. SELECT, INSERT, UPDATE on other domain tables.
-- 3. The application runtime must connect using this role, never as the 'postgres' superuser.

DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'custody_app') THEN
    CREATE ROLE custody_app WITH LOGIN PASSWORD 'CustodyAppPass702!';
  END IF;
END
$$;

-- Grant schema access
GRANT USAGE ON SCHEMA public TO custody_app;

-- Grant base table permissions
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO custody_app;

-- Strictly revoke mutation privileges on event table
-- Events are written only through append_event(), which assigns seq, prev_hash, timestamp and hash.
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON TABLE event FROM custody_app;
GRANT EXECUTE ON FUNCTION append_event(uuid, text, text, text, text, text, jsonb) TO custody_app;

-- The app role must not be able to create objects (for example look-alike functions) in this schema.
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

-- Grant sequence permissions for identity/auto-increment columns
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO custody_app;

-- Ensure future tables grant permissions correctly if needed
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO custody_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO custody_app;

-- The migration bookkeeping table is for the admin role only; the app must not edit it.
DO $$
BEGIN
  IF to_regclass('public.schema_migrations') IS NOT NULL THEN
    REVOKE ALL ON TABLE schema_migrations FROM custody_app;
  END IF;
END
$$;


COMMIT;
