-- =============================================================================
-- Custody Core: READ-ONLY check of the database after the apply script.
--
-- Paste into the Supabase dashboard > SQL Editor and click Run. It changes nothing.
-- Generated by scripts/build-deploy-sql.ts. Do not edit by hand.
--
-- Result: one row per check. The first row is the overall result: ALL PASS or N FAILED.
-- =============================================================================
WITH checks(sort, name, expected, actual) AS (
  VALUES
  (10, 'schema_migrations lists every migration (001, 002, 003, 004, 005)',
       '001_initial_schema.sql, 002_hashed_timestamp_constraint.sql, 003_database_built_event_chain.sql, 004_creator_email_not_unique.sql, 005_own_second_factor.sql',
       CASE WHEN to_regclass('public.schema_migrations') IS NULL THEN 'table schema_migrations is missing'
            ELSE COALESCE((xpath('/row/v/text()', query_to_xml('SELECT string_agg(version, '', '' ORDER BY version) AS v FROM public.schema_migrations WHERE version IN (''001_initial_schema.sql'', ''002_hashed_timestamp_constraint.sql'', ''003_database_built_event_chain.sql'', ''004_creator_email_not_unique.sql'', ''005_own_second_factor.sql'')', false, true, '')))[1]::text, 'none') END),
  (20, 'custody_app role exists', 'true', (SELECT (count(*) = 1)::text FROM pg_roles WHERE rolname = 'custody_app')),
  (30, 'custody_app has NO INSERT on event', 'false', CASE WHEN (SELECT count(*) = 1 FROM pg_roles WHERE rolname = 'custody_app') THEN has_table_privilege('custody_app', 'public.event', 'INSERT')::text ELSE 'role missing' END),
  (31, 'custody_app has NO UPDATE on event', 'false', CASE WHEN (SELECT count(*) = 1 FROM pg_roles WHERE rolname = 'custody_app') THEN has_table_privilege('custody_app', 'public.event', 'UPDATE')::text ELSE 'role missing' END),
  (32, 'custody_app has NO DELETE on event', 'false', CASE WHEN (SELECT count(*) = 1 FROM pg_roles WHERE rolname = 'custody_app') THEN has_table_privilege('custody_app', 'public.event', 'DELETE')::text ELSE 'role missing' END),
  (33, 'custody_app has NO TRUNCATE on event', 'false', CASE WHEN (SELECT count(*) = 1 FROM pg_roles WHERE rolname = 'custody_app') THEN has_table_privilege('custody_app', 'public.event', 'TRUNCATE')::text ELSE 'role missing' END),
  (34, 'custody_app CAN read event', 'true', CASE WHEN (SELECT count(*) = 1 FROM pg_roles WHERE rolname = 'custody_app') THEN has_table_privilege('custody_app', 'public.event', 'SELECT')::text ELSE 'role missing' END),
  (40, 'custody_app can EXECUTE append_event', 'true',
       CASE WHEN (SELECT count(*) = 1 FROM pg_roles WHERE rolname = 'custody_app') AND to_regprocedure('public.append_event(uuid,text,text,text,text,text,jsonb)') IS NOT NULL
            THEN has_function_privilege('custody_app', to_regprocedure('public.append_event(uuid,text,text,text,text,text,jsonb)'), 'EXECUTE')::text ELSE 'function or role missing' END),
  (41, 'the public (everyone) can NOT execute append_event', 'false',
       CASE WHEN to_regprocedure('public.append_event(uuid,text,text,text,text,text,jsonb)') IS NOT NULL
            THEN has_function_privilege('public', to_regprocedure('public.append_event(uuid,text,text,text,text,text,jsonb)'), 'EXECUTE')::text ELSE 'function missing' END),
  (42, 'append_event runs with its owner''s rights and a fixed search_path', 'true',
       COALESCE((SELECT (prosecdef AND proconfig::text LIKE '%search_path=pg_catalog, pg_temp%')::text FROM pg_proc WHERE oid = to_regprocedure('public.append_event(uuid,text,text,text,text,text,jsonb)')), 'function missing')),
  (50, 'trigger trg_event_append_only exists (blocks UPDATE and DELETE)', 'true',
       (SELECT (count(*) = 1)::text FROM pg_trigger WHERE tgrelid = to_regclass('public.event') AND tgname = 'trg_event_append_only' AND NOT tgisinternal)),
  (51, 'trigger trg_event_prevent_truncate exists (blocks TRUNCATE)', 'true',
       (SELECT (count(*) = 1)::text FROM pg_trigger WHERE tgrelid = to_regclass('public.event') AND tgname = 'trg_event_prevent_truncate' AND NOT tgisinternal)),
  (60, 'constraint chk_event_hashed_timestamp exists', 'true',
       (SELECT (count(*) = 1)::text FROM pg_constraint WHERE conrelid = to_regclass('public.event') AND conname = 'chk_event_hashed_timestamp')),
  (61, 'constraint chk_event_hash_version exists', 'true',
       (SELECT (count(*) = 1)::text FROM pg_constraint WHERE conrelid = to_regclass('public.event') AND conname = 'chk_event_hash_version')),
  (62, 'constraint chk_event_v2_canonical_payload exists', 'true',
       (SELECT (count(*) = 1)::text FROM pg_constraint WHERE conrelid = to_regclass('public.event') AND conname = 'chk_event_v2_canonical_payload')),
  (63, 'event.hashed_timestamp has no default value', 'true',
       (SELECT (column_default IS NULL)::text FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'event' AND column_name = 'hashed_timestamp')),
  (64, 'no event has an empty hashed_timestamp', '0', (SELECT count(*)::text FROM public.event WHERE hashed_timestamp = '')),
  (65, 'creator.email is not unique (a login''s email can change and be reused)', 'true',
       (SELECT (count(*) = 0)::text FROM pg_constraint con JOIN pg_attribute a ON a.attrelid = con.conrelid AND a.attnum = ANY (con.conkey)
         WHERE con.conrelid = to_regclass('public.creator') AND con.contype = 'u' AND array_length(con.conkey, 1) = 1 AND a.attname = 'email')),
  (66, 'custody_app has NO INSERT on account_event', 'false',
       CASE WHEN (SELECT count(*) = 1 FROM pg_roles WHERE rolname = 'custody_app') AND to_regclass('public.account_event') IS NOT NULL THEN has_table_privilege('custody_app', 'public.account_event', 'INSERT')::text ELSE 'table or role missing' END),
  (67, 'custody_app has NO UPDATE or DELETE on mfa_attempt (wrong-code count)', 'false',
       CASE WHEN (SELECT count(*) = 1 FROM pg_roles WHERE rolname = 'custody_app') AND to_regclass('public.mfa_attempt') IS NOT NULL
            THEN (has_table_privilege('custody_app', 'public.mfa_attempt', 'UPDATE') OR has_table_privilege('custody_app', 'public.mfa_attempt', 'DELETE'))::text ELSE 'table or role missing' END),
  (68, 'custody_app can EXECUTE append_account_event, the public can not', 'true',
       CASE WHEN (SELECT count(*) = 1 FROM pg_roles WHERE rolname = 'custody_app') AND to_regprocedure('public.append_account_event(text,text,text,text,jsonb)') IS NOT NULL
            THEN (has_function_privilege('custody_app', to_regprocedure('public.append_account_event(text,text,text,text,jsonb)'), 'EXECUTE')
                  AND NOT has_function_privilege('public', to_regprocedure('public.append_account_event(text,text,text,text,jsonb)'), 'EXECUTE'))::text
            ELSE 'function or role missing' END),
  (69, 'account_event is append-only (both triggers exist)', 'true',
       (SELECT (count(*) = 2)::text FROM pg_trigger WHERE tgrelid = to_regclass('public.account_event')
           AND tgname IN ('trg_account_event_append_only', 'trg_account_event_prevent_truncate') AND NOT tgisinternal)),
  (71, 'Supabase REST API roles (anon, authenticated) have NO rights on any Custody Core table', '0',
       (SELECT count(*)::text FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
          CROSS JOIN (SELECT rolname FROM pg_roles WHERE rolname IN ('anon', 'authenticated')) r
          CROSS JOIN unnest(ARRAY['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'TRUNCATE']) AS p(priv)
         WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p', 'v') AND has_table_privilege(r.rolname, c.oid, p.priv))),
  (72, 'Supabase REST API roles (anon, authenticated) can NOT run any Custody Core function', '0',
       (SELECT count(*)::text FROM pg_proc f JOIN pg_namespace n ON n.oid = f.pronamespace
          CROSS JOIN (SELECT rolname FROM pg_roles WHERE rolname IN ('anon', 'authenticated')) r
         WHERE n.nspname = 'public' AND has_function_privilege(r.rolname, f.oid, 'EXECUTE'))),
  (73, 'row-level security is on for every Custody Core table', '0',
       (SELECT count(*)::text FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
         WHERE n.nspname = 'public' AND c.relkind = 'r' AND NOT c.relrowsecurity)),
  (70, 'custody_app has NO access to schema_migrations', 'false',
       CASE WHEN to_regclass('public.schema_migrations') IS NULL THEN 'table schema_migrations is missing'
            ELSE CASE WHEN (SELECT count(*) = 1 FROM pg_roles WHERE rolname = 'custody_app') THEN has_table_privilege('custody_app', 'public.schema_migrations', 'SELECT')::text ELSE 'role missing' END END),
  (80, 'events whose sequence number or previous-hash link is broken (should be 0)', '0',
       (SELECT count(*)::text FROM (
          SELECT seq,
                 lag(seq)  OVER (PARTITION BY project_id ORDER BY seq) AS prev_seq,
                 prev_hash,
                 lag(hash) OVER (PARTITION BY project_id ORDER BY seq) AS prior_hash
            FROM public.event) e
         WHERE (prev_seq IS NULL AND (seq <> 1 OR prev_hash <> repeat('0', 64)))
            OR (prev_seq IS NOT NULL AND (seq <> prev_seq + 1 OR prev_hash <> prior_hash))))
),
graded AS (
  SELECT sort, name, expected, actual, CASE WHEN actual = expected THEN 'PASS' ELSE 'FAIL' END AS status FROM checks
)
SELECT 0 AS "#", CASE WHEN count(*) FILTER (WHERE status = 'FAIL') = 0 THEN 'ALL PASS' ELSE count(*) FILTER (WHERE status = 'FAIL') || ' FAILED' END AS status,
       'overall result' AS check, '' AS expected, '' AS actual
  FROM graded
UNION ALL
SELECT sort, status, name, expected, actual FROM graded
UNION ALL
SELECT 90, 'INFO', 'events written by the old method (hash_version 1) / by the database (hash_version 2)', '',
       CASE WHEN EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'event' AND column_name = 'hash_version')
            THEN (xpath('/row/v/text()', query_to_xml('SELECT (count(*) FILTER (WHERE hash_version = 1) || '' / '' || count(*) FILTER (WHERE hash_version = 2)) AS v FROM public.event', false, true, '')))[1]::text
            ELSE 'not available yet (migration 003 not applied)' END
ORDER BY 1;
